sonar.organization=sonar-ke1
sonar.projectKey=sonar-ke1_test-job
sonar.projectName=test_job
sonar.projectVersion=1.0

sonar.sources=src/main/java
sonar.tests=src/test/java

sonar.exclusions=**/node_modules/**, **/*.test.js
sonar.sourceEncoding=UTF-8

# ✅ Required for Java projects
sonar.java.binaries=target/classes