# Unique identifier for the project in SonarQube
sonar.projectKey=sonar-ke1_test-job

# Name displayed in the SonarQube UI
sonar.projectName=test_job
sonar.projectVersion=1.0

# Path to the source directories (relative to this file)
sonar.sources=src

# Encoding of the source code (default is system encoding)
sonar.sourceEncoding=UTF-8

# (Optional) Path to test files and exclusions
sonar.tests=src/test
sonar.exclusions=**/*.test.js,**/node_modules/**
